#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$ROOT"
OUT=${1:-todos.txt}
TMP="${OUT}.tmp.$$"
trap 'rm -f "$TMP"' EXIT HUP INT TERM

write_project_tree() {
    TREE_TMP="PROJECT_TREE.txt.tmp.$$"
    trap 'rm -f "$TMP" "$TREE_TMP"' EXIT HUP INT TERM
    {
        cat <<'TREE_HEADER'
# WaifuCAD project tree

Generated from the current source tree by `./make_todos.sh`. Build outputs and generated AI context are excluded.

TREE_HEADER
        find . -type f \
            ! -path './.git/*' \
            ! -path './bin/*' \
            ! -path './build/obj/*' \
            ! -path './build/tmp/*' \
            ! -path './build/tests/*' \
            ! -name '*.o' \
            ! -name '*.a' \
            ! -name '*.so' \
            ! -name '*.so.*' \
            ! -name '*.zip' \
            ! -name '*.tar.gz' \
            ! -name 'todos.txt' \
            ! -name 'PROJECT_TREE.txt' \
            ! -name 'PROJECT_TREE.txt.tmp*' \
            ! -name '*.tmp.*' \
            -print | sed 's#^./##' | LC_ALL=C sort
        printf '\n## Waifu PNG index\n\n'
        python3 - <<'PYPNG'
from pathlib import Path
import struct

for path in sorted(Path('waifus').rglob('*.png')):
    try:
        with path.open('rb') as handle:
            signature = handle.read(24)
        if len(signature) < 24 or signature[:8] != b'\x89PNG\r\n\x1a\n' or signature[12:16] != b'IHDR':
            print(f'- {path.as_posix()} — invalid PNG header')
            continue
        width, height = struct.unpack('>II', signature[16:24])
        print(f'- {path.as_posix()} — {width} × {height}')
    except OSError as exc:
        print(f'- {path.as_posix()} — unreadable: {exc}')
PYPNG
    } > "$TREE_TMP"
    mv "$TREE_TMP" PROJECT_TREE.txt
}

write_project_tree

{
    cat <<'HEADER'
# WaifuCAD AI patch context

This file is generated by `./make_todos.sh`.
It concatenates the relevant source, build, configuration, documentation,
localisation and text assets so an AI coding agent can understand the project
without first opening every file individually.

Patch rules for the AI:
- Read AGENTS.MD first and preserve its requirements.
- Keep BetterC-safe code free of GC allocation, D classes, exceptions and Phobos.
- Preserve the 64-bit-only rule: every ISA/target must have 64-bit pointers; never add RV32/x86-32/ARM32/wasm32 targets.
- Use British spelling in project code comments, documentation and UI text.
- Preserve semantic SCL journalling for every modelling mutation.
- Preserve deterministic dependency ordering when adding multicore work.
- Preserve WaifuBRep as the in-tree exact geometry kernel; do not silently substitute an external modelling kernel.
- Keep exact-vs-preview geometry status explicit when adding operators.
- Preserve the NX-like modelling spectrum: sketch/profile-driven history is preferred, but rough/free curves and non-associative dumb bodies remain first-class valid objects.
- Treat config/openscad_parity.json as the minimum SCL capability contract; do not remove an equivalent without an explicit migration decision.
- Preserve side-effect-free `use`, explicit module-child handling and Unicode scalar-value `chr`/`ord`.
- OpenSCAD .scad import/export is a dumb-body boundary: never reconstruct or emit fake parametric history.
- Sections are NX-style application contexts: Modelling is the default, each implemented Section owns its contextual ribbon, permanent Sections and Mods ribbon tabs survive Section changes, and Scripts lives as a group in the Modelling Home ribbon.
- Keep PMI code isolated under src/waifucad/sections/pmi and preserve the assembly load-policy TODO contract.
- Do not treat a target directory or policy entry as proof of a verified port.
- Prefer small reviewable patches and update AGENTS.MD TODOs when requirements change.
- Do not edit this generated file directly; edit the original files and regenerate it.

HEADER

    # Keep the root instructions first for coding agents that read only the beginning.
    for f in AGENTS.MD HANDOFF_PROMPT.md PROJECT_TREE.txt README.md LICENCE-NOTICE.md .gitignore make_todos.sh; do
        if [ -f "$f" ]; then
            printf '\n===== BEGIN FILE: %s =====\n' "$f"
            cat "$f"
            printf '\n===== END FILE: %s =====\n' "$f"
        fi
    done

    find src native config docs build ports sdk sections mods scripts tests examples assets/locales assets/themes assets/shaders assets/icons waifus \
        -type f 2>/dev/null | LC_ALL=C sort | while IFS= read -r f; do
        case "$f" in
            *.d|*.c|*.h|*.m|*.mm|*.sh|*.py|*.json|*.md|*.frag|*.vert|*.metal|*.glsl|*.svg|*.txt|*.wcs|*.scl|*.scad)
                printf '\n===== BEGIN FILE: %s =====\n' "$f"
                cat "$f"
                printf '\n===== END FILE: %s =====\n' "$f"
                ;;
        esac
    done

    printf '\n===== BEGIN FILE: build.sh =====\n'
    cat build.sh
    printf '\n===== END FILE: build.sh =====\n'
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT HUP INT TERM
printf 'Wrote %s\n' "$OUT"




